### ISSUE TITLE
Conflict with Actually Additions.

### ISSUE THREAD

**Issue by omega40k** [ModdingForBlockheads/ExCompressum#260]
So I added Ex Nihilo: Creatio & Ex Compressum to the FTB Revelations Mod pack Because I like having an automated sifting setup with drawers, so I don't have to spent so much time mining.

But, because of the uncompressed coal in Ex Compressum I can't make Tiny Torches using coal.

I know it's not a big issue. But, the only solution I can come up with is to not use Ex Compressum. And I really like Ex Compressum.

**Comment by blay09** [comment]
There's no ore-dict for "coal nuggets" right now, which is why uncompressed coal doesn't work as a substitute for the tiny coal. I'll see if we can get that fixed, though it'll probably take a bit.

Until then, Revelations probably has [CraftTweaker](https://minecraft.curseforge.com/projects/crafttweaker) installed, which means you could add a script that simply removes the Ex Compressum uncompressed coal recipe:

```
recipes.remove(<excompressum:uncompressed_coal>)
```

Didn't test the script, but it should work like that or similarly.

**Comment by omega40k** [comment]
Thanks!

**Comment by CritFlaw** [comment]
I would love an option to disable the uncompressed coal, because removing it via CT isn't an option in my pack. I've staged ex compressum and ex nihilo in a way that's not linear, just based on which dimension you're in, and that prevents CT from removing things from it.
